"""make registrations weak model

Revision ID: 1faede49f810
Revises: a9fe6c95060f
Create Date: 2025-06-03 19:48:59.049103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1faede49f810'
down_revision = 'a9fe6c95060f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.drop_constraint('_user_event_uc', type_='unique')
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.create_unique_constraint('_user_event_uc', ['user_id', 'event_id'])

    # ### end Alembic commands ###
