"""empty message

Revision ID: 40af03b939b6
Revises: 
Create Date: 2024-11-21 19:33:36.453251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40af03b939b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('max_volunteers')

    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('surname', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=15), nullable=False))
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('phone')
        batch_op.drop_column('location')
        batch_op.drop_column('surname')
        batch_op.drop_column('name')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_volunteers', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
